{
 "title": "Nodes utilization dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": " ContainersState - application node",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Nodes' CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg without(mode, cpu)(irate(node_cpu_seconds_total{ mode!=\"idle\"}[1m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Nodes' Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg without(mode, cpu)((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}