global:
  scrape_interval: 20s
scrape_configs:
  - job_name: 'application node'
    static_configs:
    - targets: ['containers:9100']
  - job_name: 'docker'
    static_configs:
      - targets: ['containers:9323']
  - job_name: 'cicd node'
    static_configs:
    - targets: ['pipelines:9100']    